[package]
name = "sglang-router-python"
version = "0.2.2"
edition = "2021"

[lib]
name = "sglang_router_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27.1", features = ["extension-module", "abi3-py38"] }

[dependencies.sglang-router]
path = "../.."
default-features = true

[features]
default = ["pyo3/extension-module"]
vendored-openssl = ["sglang-router/vendored-openssl"]
