# Basic configurations
chunk_size: 256
# enable_kv_events: true # Enable KV events

# CPU offloading configurations
local_cpu: true
use_layerwise: true
max_local_cpu_size: 10 # number of CPU backend GB
